apiVersion: move2kube.konveyor.io/v1alpha1
kind: Transformer
metadata:
  name: DockerfileImageBuildScript
  labels:
    move2kube.konveyor.io/inbuilt: true
spec:
  mode: "Container"
  class: "DockerfileImageBuildScript"
  consumes: 
    Dockerfile:
      merge: true
  directoryDetect:
    levels: 0
