apiVersion: move2kube.konveyor.io/v1alpha1
kind: Transformer
metadata:
  name: ContainerImagesPushScriptGenerator
  labels:
    move2kube.konveyor.io/inbuilt: true
spec:
  class: "ContainerImagesPushScript"
  consumes: 
    NewImages:
      merge: true
  directoryDetect:
    levels: 0
