apiVersion: move2kube.konveyor.io/v1alpha1
kind: Transformer
metadata:
  name: ContainerImagesPushScriptGenerator
  labels:
    move2kube.konveyor.io/task: containerizationscript
    move2kube.konveyor.io/built-in: true
spec:
  class: "ContainerImagesPushScript"
  directoryDetect:
    levels: 0
  consumes: 
    NewImages:
      merge: true
  produces:
    ContainerImagesPushScript:
      disabled: false
