apiVersion: move2kube.konveyor.io/v1alpha1
kind: Transformer
metadata:
  name: Jar
spec:
  mode: "Container"
  class: "JarAnalyser"
  consumes: 
    - "Jar"
  externalFiles:
    "../../common/Dockerfile.license" : templates/Dockerfile.license
    "../mappings/javapackageversions.yaml" : mappings/javapackageversions.yaml
  config: 
    defaultJavaVersion: "1.8"