apiVersion: move2kube.konveyor.io/v1alpha1
kind: Transformer
metadata:
  name: Nodejs-s2i
spec:
  mode: "Container"
  class: "Starlark"
  generates: 
    - "ContainerBuild"
  generatedBases: 
    - "ContainerBuild"
  config:
    starFile: "nodejs.star"