
FROM {{ .AppServerImage}}
# E.g.: openliberty/open-liberty:kernel-java8-openj9-ubi

EXPOSE {{.Port}}

USER root
COPY --chown=1001:0 src/main/liberty/config/server.xml /config/
COPY --chown=1001:0 target/*.jar /config/apps/
USER 1001

RUN configure.sh