apiVersion: move2kube.konveyor.io/v1alpha1
kind: Parameterizer
metadata:
  name: replicas-parameterizer
spec:
  parameterizers:
    - target: "spec.replicas"
      template: "${common.replicas}"
      keepOriginalValueIfPresent: true
      default: 2
      filters:
        - kind: Deployment