apiVersion: move2kube.konveyor.io/v1alpha1
kind: Transformer
metadata:
  name: Gradle
  labels: 
    move2kube.konveyor.io/task: containerization
    move2kube.konveyor.io/inbuilt: true
spec:
  class: "GradleAnalyser"
  consumes:
    Service: 
      merge: false
  externalFiles:
    "../../common/Dockerfile.license" : templates/Dockerfile.license
    "../mappings/javapackageversions.yaml" : mappings/javapackageversions.yaml
  config: 
    defaultJavaVersion: "1.8"