# FROM quay.io/konveyor/tca-service-api
# FROM quay.io/mihirc36/tackle-container-advisor
FROM quay.io/konveyor/tackle-container-advisor:v1.1.0

COPY detect.py transform.py preprocess.py cfservices.yaml ./
