apiVersion: move2kube.konveyor.io/v1alpha1
kind: Transformer
metadata:
  name: Kubernetes
  labels:
    move2kube.konveyor.io/inbuilt: true
spec:
  class: "Kubernetes"
  directoryDetect:
    levels: 0
  consumes:
    IR:
      merge: true
  produces:
    KubernetesYamls:
      disabled: false
  dependency:
    matchLabels:
      move2kube.konveyor.io/kubernetesclusterselector: "true"
  config:
    outputPath: "deploy/yamls"
    ingressName: "{{ .ProjectName }}"
