apiVersion: move2kube.konveyor.io/v1alpha1
kind: Transformer
metadata:
  name: ComposeAnalyser
  labels:
    move2kube.konveyor.io/inbuilt: true
spec:
  class: "ComposeAnalyser"
  directoryDetect:
    levels: 1
  consumes:
    Service:
      disabled: false
  produces:
    IR:
      disabled: false
