apiVersion: move2kube.konveyor.io/v1alpha1
kind: Transformer
metadata:
  name: Knative
  labels:
    move2kube.konveyor.io/inbuilt: true
spec:
  class: "Knative"
  directoryDetect:
    levels: 0
  consumes:
    IR:
      merge: true
  produces:
    KubernetesYamls:
      disabled: false
