apiVersion: move2kube.konveyor.io/v1alpha1
kind: Transformer
metadata:
  name: Python-Dockerfile
  labels: 
    move2kube.konveyor.io/task: containerization
    move2kube.konveyor.io/inbuilt: true
spec:
  class: "PythonDockerfileGenerator"
  consumes:
    Service: 
      merge: false
