apiVersion: move2kube.konveyor.io/v1alpha1
kind: Transformer
metadata:
  name: Parameterizer
spec:
  class: "Parameterizer"
  consumes:
    KubernetesYamls:
      merge: true
  directoryDetect:
    levels: 0
