
FROM registry.access.redhat.com/ubi8/ubi:latest AS builder
RUN yum install -y {{ .JavaPackageName }}
RUN yum install -y maven
COPY . /app
WORKDIR /app
{{if .MavenProfiles}}RUN mvn package -Dmaven.test.skip -P {{$first := true}}{{range $mp := .MavenProfiles}}{{if $first}}{{$first = false}}{{else}},{{end}}{{$mp}}{{end}}{{else}}RUN mvn package -Dmaven.test.skip{{end}}