
FROM registry.access.redhat.com/ubi8/ubi:latest AS builder
RUN yum install -y {{ .JavaPackageName }}
RUN yum install -y maven
COPY . /app
WORKDIR /app

{{- range $mp := .MavenProfiles }}
{{ $mp }}
{{- end }}

RUN mvn package

