apiVersion: move2kube.konveyor.io/v1alpha1
kind: Transformer
metadata:
  name: Liberty
  labels:
    move2kube.konveyor.io/built-in: true
    move2kube.konveyor.io/warprocessor: true
    move2kube.konveyor.io/earprocessor: true
spec:
  class: "Liberty"
  directoryDetect:
    levels: 0
  consumes:
    War:
      merge: false
    Ear:
      merge: false
  produces:
    Dockerfile:
      disabled: false
    DockerfileForService:
      disabled: false
  externalFiles:
    "../../common/Dockerfile.license": templates/Dockerfile.license
    "../mappings/javapackageversions.yaml": mappings/javapackageversions.yaml
  config:
    defaultJavaVersion: "17"
