apiVersion: move2kube.konveyor.io/v1alpha1
kind: Transformer
metadata:
  name: Django
spec:
  mode: "Container"
  class: "SimpleExecutable"
  generates: 
    - "ContainerBuild"
  generatedBases: 
    - "ContainerBuild"
  config:
    directoryDetectCMD: ["./m2kdetect.sh"]
    platforms: ["linux", "darwin"]
