apiVersion: move2kube.konveyor.io/v1alpha1
kind: Transformer
metadata:
  name: ContainerImagesPushScript
spec:
  class: "ContainerImagesPushScript"
  consumes: 
    NewImages:
      merge: true
  directoryDetect:
    levels: 0
