apiVersion: move2kube.konveyor.io/v1alpha1
kind: Transformer
metadata:
  name: Java-Springboot-Runtime
spec:
  mode: "Container"
  class: "SpringbootRuntimeAnalyser"
  consumes: 
    - "BuildType"
    - "RuntimeType"