apiVersion: move2kube.konveyor.io/v1alpha1
kind: Transformer
metadata:
  name: Buildconfig
spec:
  mode: "Container"
  class: "BuildConfig"
  consumes:
    - "IR"
  generates:
    - "KubernetesYamls"
