apiVersion: move2kube.konveyor.io/v1alpha1
kind: Transformer
metadata:
  name: ZuulAnalyser
  labels: 
    move2kube.konveyor.io/inbuilt: true
spec:
  class: "ZuulAnalyser"
  directoryDetect:
    levels: 0
  consumes:
    IR: 
      merge: true
      mode: "MandatoryPassThrough"
  produces:
    IR:
      disabled: false
