apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: "sub-to-{{ .OperatorName }}"
spec:
  channel: "{{ .CatalogChannel }}"
  name: "{{ .OperatorName }}"
  source: "{{ .CatalogSource }}"
  installPlanApproval: "{{ .InstallPlanApproval }}"
