/*
 *  Copyright IBM Corporation 2021
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

package kubernetes

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/konveyor/move2kube/common"
	"github.com/konveyor/move2kube/environment"
	"github.com/konveyor/move2kube/transformer/kubernetes/k8sschema"
	"github.com/konveyor/move2kube/transformer/kubernetes/parameterizer"
	transformertypes "github.com/konveyor/move2kube/types/transformer"
	"github.com/konveyor/move2kube/types/transformer/artifacts"
	"github.com/sirupsen/logrus"
)

const (
	helmPathTemplateName       = "HelmPath"
	kustomizePathTemplateName  = "KustomizePath"
	ocTemplatePathTemplateName = "OCTemplatePath"
)

const (
	// ExtraParameterizersConfigType stores extra parameterizers generated by other transformers
	ExtraParameterizersConfigType transformertypes.ConfigType = "ExtraParameterizers"
)

// Parameterizer implements Transformer interface
type Parameterizer struct {
	Config              transformertypes.Transformer
	Env                 *environment.Environment
	ParameterizerConfig *ParameterizerYamlConfig
	parameterizers      []parameterizer.ParameterizerT
}

// ParameterizerYamlConfig implements Parameterizer path config interface
type ParameterizerYamlConfig struct {
	HelmPath       string   `yaml:"helmPath" json:"helmPath"`
	OCTemplatePath string   `yaml:"ocTemplatePath" json:"ocTemplatePath"`
	KustomizePath  string   `yaml:"kustomizePath" json:"kustomizePath"`
	ProjectName    string   `yaml:"projectName" json:"projectName"`
	Envs           []string `yaml:"envs,omitempty" json:"envs,omitempty"`
}

// ParameterizerPathTemplateConfig stores the template config
type ParameterizerPathTemplateConfig struct {
	YamlsPath        string
	ServiceFsPath    string
	PathTemplateName string
}

// Init Initializes the transformer
func (paramTransformer *Parameterizer) Init(tc transformertypes.Transformer, e *environment.Environment) error {
	paramTransformer.Config = tc
	paramTransformer.Env = e
	paramTransformer.ParameterizerConfig = &ParameterizerYamlConfig{}
	if err := common.GetObjFromInterface(paramTransformer.Config.Spec.Config, paramTransformer.ParameterizerConfig); err != nil {
		return fmt.Errorf("failed to load the config %+v into the type %T . Error: %w", paramTransformer.Config.Spec.Config, paramTransformer.ParameterizerConfig, err)
	}
	if paramTransformer.ParameterizerConfig.ProjectName == "" {
		paramTransformer.ParameterizerConfig.ProjectName = e.ProjectName
	}
	paramsMap, err := parameterizer.CollectParamsFromPath(paramTransformer.Env.Context)
	if err != nil {
		return fmt.Errorf("failed to collect parameterizers from the directory at path '%s' . Error: %w", paramTransformer.Env.Context, err)
	}
	for _, params := range paramsMap {
		paramTransformer.parameterizers = append(paramTransformer.parameterizers, params...)
	}
	return nil
}

// GetConfig returns the transformer config
func (paramTransformer *Parameterizer) GetConfig() (transformertypes.Transformer, *environment.Environment) {
	return paramTransformer.Config, paramTransformer.Env
}

// DirectoryDetect runs detect in each subdirectory
func (paramTransformer *Parameterizer) DirectoryDetect(dir string) (namedServices map[string][]transformertypes.Artifact, err error) {
	k8sResMap, err := k8sschema.GetK8sResourcesWithPaths(dir, true)
	if err != nil {
		logrus.Debugf("failed to get K8s resources from the directory '%s' . Error: %q", dir, err)
		return nil, nil
	}
	for _, kList := range k8sResMap {
		for _, k := range kList {
			_, _, _, err := k8sschema.GetInfoFromK8sResource(k)
			if err == nil {
				na := transformertypes.Artifact{
					Paths: map[transformertypes.PathType][]string{
						artifacts.KubernetesYamlsPathType: {dir},
						artifacts.ServiceDirPathType:      {dir},
					},
				}
				return map[string][]transformertypes.Artifact{"": {na}}, nil
			}
		}
	}
	return nil, nil
}

// Transform transforms artifacts
func (paramTransformer *Parameterizer) Transform(
	newArtifacts []transformertypes.Artifact,
	alreadySeenArtifacts []transformertypes.Artifact,
) (pathMappings []transformertypes.PathMapping, createdArtifacts []transformertypes.Artifact, err error) {
	pathMappings = []transformertypes.PathMapping{}
	for _, newArtifact := range newArtifacts {
		if len(newArtifact.Paths[artifacts.KubernetesYamlsPathType]) == 0 {
			continue
		}
		yamlsPath := newArtifact.Paths[artifacts.KubernetesYamlsPathType][0]
		tempPath, err := os.MkdirTemp(paramTransformer.Env.TempPath, "*")
		if err != nil {
			logrus.Errorf("failed to create the temp directory '%s' . Error: %q", paramTransformer.Env.TempPath, err)
			continue
		}
		baseDirName := filepath.Base(yamlsPath) + "-parameterized"
		destPath := filepath.Join(tempPath, baseDirName)
		var sConfig artifacts.ServiceConfig
		if err := newArtifact.GetConfig(artifacts.ServiceConfigType, &sConfig); err != nil {
			logrus.Debugf("failed to load config of type '%s' into struct of type %T . Error: %q", artifacts.ServiceConfigType, sConfig, err)
		}
		moreParams := []parameterizer.ParameterizerT{}
		if err := newArtifact.GetConfig(ExtraParameterizersConfigType, &moreParams); err != nil {
			logrus.Debugf("failed to load config of type '%s' into struct of type %T . Error: %q", ExtraParameterizersConfigType, moreParams, err)
		}
		projectName, err := common.GetStringFromTemplate(paramTransformer.ParameterizerConfig.ProjectName,
			map[string]string{common.ProjectNameTemplatizedStringKey: paramTransformer.Env.ProjectName,
				common.ArtifactNameTemplatizedStringKey: newArtifact.Name,
				common.ServiceNameTemplatizedStringKey:  sConfig.ServiceName,
				common.ArtifactTypeTemplatizedStringKey: string(newArtifact.Type)})
		if err != nil {
			logrus.Errorf("failed to fill the project name template. Error: %q", err)
			continue
		}
		pt := parameterizer.ParameterizerConfigT{
			Helm:        "helm",
			Kustomize:   "kustomize",
			OCTemplates: "octemplates",
			ProjectName: projectName,
			Envs:        []string{},
		}
		if len(paramTransformer.ParameterizerConfig.Envs) > 0 {
			pt.Envs = paramTransformer.ParameterizerConfig.Envs
		}
		if len(paramTransformer.ParameterizerConfig.HelmPath) == 0 {
			pt.Helm = ""
		}
		if len(paramTransformer.ParameterizerConfig.KustomizePath) == 0 {
			pt.Kustomize = ""
		}
		if len(paramTransformer.ParameterizerConfig.OCTemplatePath) == 0 {
			pt.OCTemplates = ""
		}
		filesWritten, err := parameterizer.Parameterize(yamlsPath, destPath, pt, append(paramTransformer.parameterizers, moreParams...))
		if err != nil {
			logrus.Errorf(
				"failed to parameterize the YAML files in the source directory '%s' and write to the output directory '%s' . Error: %q",
				yamlsPath, destPath, err,
			)
			continue
		}
		logrus.Debugf("Number of files written by parameterizer: %d", len(filesWritten))

		helmKey := helmPathTemplateName + common.GetRandomString()
		kustomizeKey := kustomizePathTemplateName + common.GetRandomString()
		octKey := ocTemplatePathTemplateName + common.GetRandomString()

		serviceFsPath := ""
		if serviceFsPaths, ok := newArtifact.Paths[artifacts.ServiceDirPathType]; ok && len(serviceFsPaths) > 0 {
			serviceFsPath = serviceFsPaths[0]
		}
		if len(paramTransformer.ParameterizerConfig.HelmPath) != 0 {
			pathMappings = append(pathMappings, transformertypes.PathMapping{
				Type:           transformertypes.PathTemplatePathMappingType,
				SrcPath:        paramTransformer.ParameterizerConfig.HelmPath,
				TemplateConfig: ParameterizerPathTemplateConfig{YamlsPath: yamlsPath, PathTemplateName: helmKey, ServiceFsPath: serviceFsPath},
			})
			pathMappings = append(pathMappings, transformertypes.PathMapping{
				Type:     transformertypes.DefaultPathMappingType,
				SrcPath:  filepath.Join(destPath, pt.Helm),
				DestPath: fmt.Sprintf("{{ .%s }}", helmKey),
			})
		}
		if len(paramTransformer.ParameterizerConfig.KustomizePath) != 0 {
			pathMappings = append(pathMappings, transformertypes.PathMapping{
				Type:           transformertypes.PathTemplatePathMappingType,
				SrcPath:        paramTransformer.ParameterizerConfig.KustomizePath,
				TemplateConfig: ParameterizerPathTemplateConfig{YamlsPath: yamlsPath, PathTemplateName: kustomizeKey, ServiceFsPath: serviceFsPath},
			})
			pathMappings = append(pathMappings, transformertypes.PathMapping{
				Type:     transformertypes.DefaultPathMappingType,
				SrcPath:  filepath.Join(destPath, pt.Kustomize),
				DestPath: fmt.Sprintf("{{ .%s }}", kustomizeKey),
			})
		}
		if len(paramTransformer.ParameterizerConfig.OCTemplatePath) != 0 {
			pathMappings = append(pathMappings, transformertypes.PathMapping{
				Type:           transformertypes.PathTemplatePathMappingType,
				SrcPath:        paramTransformer.ParameterizerConfig.OCTemplatePath,
				TemplateConfig: ParameterizerPathTemplateConfig{YamlsPath: yamlsPath, PathTemplateName: octKey, ServiceFsPath: serviceFsPath},
			})
			pathMappings = append(pathMappings, transformertypes.PathMapping{
				Type:     transformertypes.DefaultPathMappingType,
				SrcPath:  filepath.Join(destPath, pt.OCTemplates),
				DestPath: fmt.Sprintf("{{ .%s }}", octKey),
			})
		}
	}
	return pathMappings, nil, nil
}
