apiVersion: move2kube.konveyor.io/v1alpha1
kind: Transformer
metadata:
  name: Buildconfig
  labels:
    move2kube.konveyor.io/built-in: true
spec:
  class: "BuildConfig"
  directoryDetect:
    levels: 0
  consumes:
    IR:
      merge: true
  produces:
    KubernetesYamls:
      disabled: false
  dependency:
    matchLabels:
      move2kube.konveyor.io/kubernetesclusterselector: "true"
  config:
    outputPath: "deploy/cicd/buildconfig"
    setDefaultValuesInYamls: false
