apiVersion: move2kube.konveyor.io/v1alpha1
kind: Transformer
metadata:
  name: Tomcat
  labels:
    move2kube.konveyor.io/built-in: true
    move2kube.konveyor.io/warprocessor: true
spec:
  class: "Tomcat"
  directoryDetect:
    levels: 0
  consumes: 
    War:
      merge: false
  produces:
    Dockerfile:
      disabled: false
    DockerfileForService:
      disabled: false
  externalFiles:
    "../../common/Dockerfile.license" : templates/Dockerfile.license
    "../mappings/javapackageversions.yaml" : mappings/javapackageversions.yaml
  config: 
    defaultJavaVersion: "17"
