apiVersion: move2kube.konveyor.io/v1alpha1
kind: Transformer
metadata:
  name: Golang-Dockerfile
  labels: 
    move2kube.konveyor.io/task: containerization
    move2kube.konveyor.io/inbuilt: true
spec:
  class: "GolangDockerfileGenerator"
  directoryDetect:
    levels: -1
  consumes:
    Service: 
      merge: false
  produces:
    Dockerfile:
      disabled: false
    DockerfileForService:
      disabled: false
  config:
    defaultGoVersion: "1.17"
