apiVersion: move2kube.konveyor.io/v1alpha1
kind: Transformer
metadata:
  name: DockerfileDetector
  labels:
    move2kube.konveyor.io/inbuilt: true
spec:
  class: "DockerfileDetector"
  directoryDetect:
    levels: 1
