apiVersion: move2kube.konveyor.io/v1alpha1
kind: Transformer
metadata:
  name: DockerfileDetector
spec:
  mode: "Container"
  class: "DockerfileDetector"
  generates: 
    - "ContainerBuild"
    - "Dockerfile"
  generatedBases: 
    - "ContainerBuild"
