apiVersion: move2kube.konveyor.io/v1alpha1
kind: Transformer
metadata:
  name: GCRCNBContainerizer
spec:
  mode: "Container"
  class: "CNBContainerizer"
  config:
    CNBBuilder: "gcr.io/buildpacks/builder"
