
FROM registry.access.redhat.com/ubi8/ubi:latest AS builder
RUN yum install -y {{ .JavaPackageName }}{{ if not .GradleWPresent }}
RUN yum install -y wget unzip
RUN wget https://services.gradle.org/distributions/gradle-{{ .GradleVersion }}-bin.zip -P /tmp && unzip -d /opt/gradle /tmp/gradle-{{ .GradleVersion }}-bin.zip && rm -rf /tmp/gradle-{{ .GradleVersion }}-bin.zip
ENV PATH="$PATH:/opt/gradle/gradle-{{ .GradleVersion }}/bin/"{{- end }}
WORKDIR /app
COPY . .
{{ if .GradleWPresent }}RUN ./gradlew assemble{{ else }}RUN gradle wrapper && ./gradlew assemble{{ end }}