apiVersion: move2kube.konveyor.io/v1alpha1
kind: Transformer
metadata:
  name: Nodejs-Dockerfile
  labels:
    move2kube.konveyor.io/task: containerization
    move2kube.konveyor.io/inbuilt: true
spec:
  class: "NodejsDockerfileGenerator"
  consumes:
    Service: 
      merge: false
  config:
    defaultNodejsVersion: "12"
