apiVersion: move2kube.konveyor.io/v1alpha1
kind: Transformer
metadata:
  name: DotNetCore-Dockerfile
  labels:
    move2kube.konveyor.io/task: containerization
    move2kube.konveyor.io/built-in: true
spec:
  class: "DotNetCoreDockerfileGenerator"
  directoryDetect:
    levels: -1
  consumes:
    Service: 
      merge: false
  produces:
    Dockerfile:
      disabled: false
    DockerfileForService:
      disabled: false
  config:
      defaultDotNetCoreVersion: "5.0"
