
FROM registry.access.redhat.com/ubi8/ubi-minimal:latest
RUN microdnf update \
   && microdnf install --nodocs \
      {{ .JavaPackageName }} \
   && microdnf clean all
ENV {{ .PortConfigureEnvName }} {{ .Port }}
COPY --from=builder {{ .DeploymentFileDir }} .
EXPOSE {{ .Port }}
CMD ["java", "-jar", "{{ .DeploymentFile }}"]