apiVersion: move2kube.konveyor.io/v1alpha1
kind: Transformer
metadata:
  name: CNBContainerizer
spec:
  mode: "Container"
  class: "CNBContainerizer"
  generates: 
    - "ContainerBuild"
  generatedBases: 
    - "ContainerBuild"
  config:
    CNBBuilder: "cloudfoundry/cnb:cflinuxfs3"
