apiVersion: move2kube.konveyor.io/v1alpha1
kind: Transformer
metadata:
  name: ReadMeGenerator
  labels:
    move2kube.konveyor.io/inbuilt: true
spec:
  class: "ReadMeGenerator"
  consumes: 
    ContainerImagesPushScript:
      merge: true
    ContainerImagesBuildScript:
      merge: true
    KubernetesYamls:
      merge: true
  directoryDetect:
    levels: 0
