apiVersion: move2kube.konveyor.io/v1alpha1
kind: Transformer
metadata:
  name: EarAnalyser
  labels:
    move2kube.konveyor.io/task: containerization
    move2kube.konveyor.io/built-in: true
spec:
  class: "EarAnalyser"
  directoryDetect:
    levels: -1
  consumes:
    Service: 
      merge: false
  produces:
    Ear:
      disabled: false
  config: 
    defaultJavaVersion: "17"
