apiVersion: move2kube.konveyor.io/v1alpha1
kind: Transformer
metadata:
  name: DockerfileDetector
  labels:
    move2kube.konveyor.io/built-in: true
spec:
  class: "DockerfileDetector"
  directoryDetect:
    levels: 1
  consumes:
    Service:
      disabled: false
  produces:
    Dockerfile:
      disabled: false
    DockerfileForService:
      disabled: false
