apiVersion: move2kube.konveyor.io/v1alpha1
kind: Transformer
metadata:
  name: Jboss
  labels:
    move2kube.konveyor.io/inbuilt: true
    move2kube.konveyor.io/warprocessor: true
    move2kube.konveyor.io/earprocessor: true
spec:
  class: "Jboss"
  consumes: 
    Jboss:
      merge: false
  directoryDetect:
    levels: 0
  externalFiles:
    "../../common/Dockerfile.license" : templates/Dockerfile.license
    "../mappings/javapackageversions.yaml" : mappings/javapackageversions.yaml
  config: 
    defaultJavaVersion: "1.8"
