apiVersion: move2kube.konveyor.io/v1alpha1
kind: Transformer
metadata:
  name: Jboss
  labels:
    move2kube.konveyor.io/inbuilt: true
    move2kube.konveyor.io/artifacttoprocess: war
spec:
  class: "Jboss"
  consumes: 
    Jobss:
      merge: false
  externalFiles:
    "../../common/Dockerfile.license" : templates/Dockerfile.license
    "../mappings/javapackageversions.yaml" : mappings/javapackageversions.yaml
  config: 
    defaultJavaVersion: "1.8"
