apiVersion: move2kube.konveyor.io/v1alpha1
kind: Transformer
metadata:
  name: WinSLWebApp-Dockerfile
  labels: 
    move2kube.konveyor.io/task: containerization
    move2kube.konveyor.io/inbuilt: true
spec:
  class: "WinSilverLightWebAppDockerfileGenerator"
