apiVersion: move2kube.konveyor.io/v1alpha1
kind: Transformer
metadata:
  name: Golang
spec:
  mode: "Container"
  class: "SimpleExecutable"
  generates: 
    - "ContainerBuild"
  generatedBases: 
    - "ContainerBuild"
  config:
    directoryDetectCMD: ["./m2kdetect.sh"]
    #container:
    #  image: m2kgolangdf
    #  build:
    #    dockerfile: Dockerfile
    #    context: .
