apiVersion: move2kube.konveyor.io/v1alpha1
kind: Transformer
metadata:
  name: Maven
  labels: 
    move2kube.konveyor.io/task: containerization
    move2kube.konveyor.io/built-in: true
spec:
  class: "MavenAnalyser"
  directoryDetect:
    levels: -1
  consumes:
    Service:
      disabled: false
  produces:
    Jar:
      disabled: false
    War:
      disabled: false
    Ear:
      disabled: false
    Dockerfile:
      disabled: false
  externalFiles:
    "../../common/Dockerfile.license" : templates/Dockerfile.license
    "../mappings/javapackageversions.yaml" : mappings/javapackageversions.yaml
  config: 
    defaultMavenVersion: "3.8.4"
    defaultJavaVersion: "17"
    appPathInBuildContainer: "/app"