name: Assign Project

on:
  issues:
    types: [opened]

jobs:
  create_card:
    runs-on: ubuntu-latest
    steps:
      - name: create project card
        uses: peter-evans/create-or-update-project-card@v1
        with:
          token: ${{ secrets.MOVE2KUBE_PATOKEN }}
          project-name: Move2Kube
          column-name: Backlog
          project-location: konveyor
