name: Trigger end to end tests

on:
  push:
    branches:
      - "main"

jobs:
  trigger-e2e-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.MOVE2KUBE_PATOKEN }}
          script: |
            const e2e_tests = ['e2etest-1-language-platforms.yaml', 'e2etest-2-enterprise-app.yaml'];
            const promises = e2e_tests.map(workflow_id => github.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: 'move2kube-tests',
              workflow_id,
              ref: 'main',
              inputs: {tag: 'main'},
            }));
            await Promise.all(promises);
