name: move2kube

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.15
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - uses: actions/cache@v2
      with:
        path: "$GOPATH/pkg/mod"
        key: ${{ runner.os }}

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build and Test 
      run: make ci
