name: PR Build

on:
  pull_request:
    branches:
      - "main"
      - "release-*"

jobs:
  build_and_test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: info
        uses: konveyor/get-env-info@v1
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ steps.info.outputs.go_version }}
      - run: make ci
      - run: make test-coverage
      - name: upload coverage
        uses: codecov/codecov-action@v1
