name: build

on:
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: Check out code
      uses: actions/checkout@v2

    - name: Build and Test 
      run: make ci

    - name: Test Coverage
      run: make test-coverage

    - name: Upload Coverage
      uses: codecov/codecov-action@v1
