name: Publish Release Drafts

on:
  workflow_dispatch:
    inputs:
      owner_repo_ids:
        description: |
          owner_repo_ids: JSON array of { owner: string, repo: string, release_id: number } objects.
          All the listed release drafts will be published.
        required: true

jobs:
  publish:
    name: Publish release drafts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.MOVE2KUBE_PATOKEN }}
          script: |
            const update_release_info_workflow = 'releaseinfo.yml';
            const owner_repo_ids = JSON.parse('${{ github.event.inputs.owner_repo_ids }}');

            const promises = owner_repo_ids.map(owner_repo_id => github.repos.updateRelease({...owner_repo_id, draft: false}));
            await Promise.all(promises);

            await github.actions.createWorkflowDispatch({
                ...context.repo,
                workflow_id: update_release_info_workflow,
                ref: context.ref,
            });
