name: Publish Release Drafts

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Tag of the release drafts
        required: true
        default: v0.1.0-rc.2

jobs:
  publish:
    name: Publish release drafts
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo:
          [
            "move2kube",
            "move2kube-api",
            "move2kube-ui",
            "move2kube-operator",
            "move2kube-tests",
          ]
    steps:
      - id: get_release_draft_id
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.MOVE2KUBE_PATOKEN }}
          script: |
            const owner = "konveyor";
            const repo = "${{ matrix.repo }}";
            const tag = "${{ github.event.inputs.tag }}";
            const response = await github.repos.listReleases({ owner, repo });
            for (const release of response.data) {
              core.debug(release.tag_name);
              if (release.tag_name === tag) {
                core.info(`Found a release with the tag ${tag} and ID ${release.id}`);
                core.setOutput("id", release.id);
                return;
              }
            }
            core.setFailed(`Failed to find a release with the tag ${tag}`);
      - name: publish
        uses: StuYarrow/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MOVE2KUBE_PATOKEN }}
        with:
          repo: ${{ matrix.repo }}
          id: ${{ steps.get_release_draft_id.outputs.id }}
