name: Tag

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag Name"
        required: true
        default: "v0.1.0-rc.2"

jobs:
  tag:
    name: Tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.MOVE2KUBE_PATOKEN }}
          script: |
            github.git.createRef({
              ...context.repo.owner,
              ref: "refs/tags/${{ github.event.inputs.tag }}",
              sha: context.sha
            })
