name: Tag

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag name"
        required: true
        default: "v0.1.0-rc.2"
      sha:
        description: "SHA of the commit to tag. Defaults to latest commit on branch this was invoked on."
        required: false

jobs:
  tag:
    name: Tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.MOVE2KUBE_PATOKEN }}
          script: |
            const sha = '${{ github.event.inputs.sha }}' || context.sha;
            await github.git.createRef({
              ...context.repo,
              ref: 'refs/tags/${{ github.event.inputs.tag }}',
              sha
            });
