
FROM websphere-liberty:webProfile8
COPY --chown=1001:0 {{ if .BuildContainerName }}--from=builder {{ .DeploymentFileDirInBuildContainer }}/{{end}}{{ .DeploymentFile }} /config/dropins/
EXPOSE {{ .Port }}