
FROM {{ .LibertyBaseImage }}
{{- range $k, $v := .EnvVariables}}
ENV {{$k}} {{$v}}
{{- end}}
COPY --chown=1001:0 {{ if .BuildContainerName }}--from=builder {{ .DeploymentFileDirInBuildContainer }}/{{end}}{{ .DeploymentFile }} /config/dropins/
EXPOSE {{ .Port }}